deploy:
  image: gcr.io/cloud-builders/gcloud-slim
  only:
    - main
  script:
    - gcloud auth activate-service-account --key-file $GCR_CREDENTIALS
    - gcloud functions deploy gitlabToMQTT --allow-unauthenticated --region=europe-west3 --memory=128MB --runtime=nodejs16 --trigger-http --set-env-vars=MQTT_URL=$MQTT_URL,MQTT_TOPIC=$MQTT_TOPIC,GITLAB_TOKEN=$GITLAB_TOKEN
