image: gcr.io/hedenstroem-docker/gitlab-builder-base

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - vaultenv download secret/gitlab-ci/gcf-deploy@hedenstroem-gitlab.json ~/gcf-deploy.json
    - gcloud auth activate-service-account --key-file ~/gcf-deploy.json
    - gcloud functions deploy relayToMQTT --runtime nodejs10 --trigger-http
